First iteration of calendar
iMeisa/serserilig.meisa.xyz pull request #2
Opened 2022-04-16 20:51 UTC by lutrarutra

Created pages:
- /calendar (responsive)
- /edit/calendar (not small screen friendly)

Implementation summary:
- Races (templated from /static/json/gp_references.json) can be added to calendar. Same circuit can be added as many times as one wishes. 
- Time and date for each race are stored separately as text. 
- Calendar is stored in `races`-table with 4 columns: id (PK), gp_id (reference to GP from `statc/json/gp_reference.json`), date, and time
- DB is cached to /static/json/calendar.json.
- Cache is included in `.gitignore`

2022-04-16 21:06 UTC, iMeisa commented on internal/handlers/admin.go
> -	dataMap := make(map[string]interface{})
Non essential removal of functions

2022-04-16 21:17 UTC, iMeisa requested changes
Couple of changes and then should be good for merge

2022-04-16 21:17 UTC, iMeisa commented on internal/models/templatedata.go
> +
Sort will be done by SQL. (No changes for pull request)

2022-04-16 21:17 UTC, iMeisa commented on templates/base.layout.tmpl
> +                    <li class="nav-item"><a class="nav-link" href="/calendar" id="nav-grid">Calendar</a></li>
Change id to nav-calendar

2022-04-16 21:57 UTC, lutrarutra commented on internal/handlers/admin.go
> -	dataMap := make(map[string]interface{})
Done in [f4491f1](https://github.com/iMeisa/serserilig.meisa.xyz/pull/2/commits/f4491f1f1396444f89e6ab4ff28365876491d598)

2022-04-17 10:25 UTC, iMeisa approved these changes

2022-04-17 10:28 UTC, merged